root: true
env:
    browser: true
    commonjs: true
    es2021: true
extends:
    - "eslint:recommended"
    - "plugin:@typescript-eslint/strict-type-checked"
    - prettier
parser: "@typescript-eslint/parser"
parserOptions:
    project: true
    tsconfigRootDir: __dirname
plugins:
    - "@typescript-eslint"
ignorePatterns: ["*.js", "jest.config.ts"]
